version: "3"

services:
  revive:
    build: 
      context: .
      dockerfile: $PWD/docker/Dockerfile
    container_name: revive-app
    ports:
      - "8080:80"
    volumes:
      - $PWD/server/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/docker/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - $PWD/data/app:/var/www/html
    networks:
      - revivenet
  mysql:
    image: mysql:5.7
    container_name: revive-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - $PWD/data/mysql:/var/lib/mysql
    networks:
      - revivenet

networks:
  revivenet:
    driver: bridge